### ISSUE TITLE
typos in readme

### ISSUE THREAD

**Issue by stephkramer** [EcoDynIZW/EcoDynIZW#1]
Hi there (Moritz?), nice intro. Maybe some more info, not only Leibniz IZW, but the full name here? And a link to our institute as well as a bit of explanation,  in the text below, what can be seen on the intro picture.
And take care, we are the Department OF Ecological DynamicS...

**Comment by z3tt** [comment]
I fixed the typos and added the link to the repository of the accepted study by Marescot, Franz, Benhaiem et al.
